baseURL = "https://ytplaylist.satriafii.social/"
languageCode = "en-us"
theme = "glim-midnight"

[params]
    title = "Youtube Playlist because I need it"
    phrases = ["What are you looking at?", "Just listen to these songs", "And be happy", "What? You want more?", "Are you lonely?", "Gabut banget kah sampe baca ini ._.", "Yaudah sini aku ceritain sesuatu", "Sebenernya", "Aku", "Nggak ada cerita apa-apa sih.", "what do you expect from homey girl?", "Some good banger stories?", "nah, bro. I just as gabut as you are.", "Are you hungry?", "Don't forget to eat.", "It's funny cause who the fuck have time to forget to eat?", "Well, maybe you have so much work?", "But don't you feel your stomach hurting??", "Anyway. Have a nice day.", "won't say goodbye tho.", "cause you still reading this shit.", "hope you smilling reading this.", "cause I'm not when I write this.", "But now I smile.", "really.", "like this 😊", "So, how do you smile?", "That's a good smile.", "keep doing it."]
    links = [
    {name = "K-Band ❤️", url = "https://www.youtube.com/playlist?list=PLbX78G3bHcTk02blTJlq1EaUoL9BAXBNz"},    
    {name = "MAMAMOO Immortal Songs Performances", url = "https://www.youtube.com/playlist?list=PLzzl7xuKwGRP24e6iktfq5pkev_Ii0jx4"},    
    {name = "ONEWE Kanghyun's BGM", url = "https://www.youtube.com/playlist?list=PLbX78G3bHcTnRLJ9CB68JZpGtmCh5noVl"},    
    {name = "albums that I freaking love", url = "https://www.youtube.com/playlist?list=PL0AhFxILKAXj8IH66HGqgUFiSwB7SdoCW"},    
    {name = "when gabut", url = "https://www.youtube.com/playlist?list=PL0AhFxILKAXiRvFGkB5ZjLgxHSITZlAyT"},
    {name = "After Work", url = "https://www.youtube.com/playlist?list=PL0AhFxILKAXgyvgzovyhaJ5cbiHAFKdND"},
    {name = "Starting Work", url = "https://www.youtube.com/playlist?list=PL0AhFxILKAXg9EjMHp_vGDq9aQukdsRsh"},
    {name = "2010 is a music genre", url = "https://www.youtube.com/playlist?list=PLRizQinsCsRnVpBSh-50aI3WThjL8uXSl"},
    {name = "nsfw", url = "https://www.youtube.com/playlist?list=PLRizQinsCsRkzBY1Zlr8999md0Ou8cCKR"},
    {name = "PoP GooD", url = "https://music.youtube.com/playlist?list=PLE_uhVAa3GZtveY_EkrYKlIIc9r92qgxY"},
    {name = "Funny Playlist", url = "https://music.youtube.com/playlist?list=PLE_uhVAa3GZuJeiLUVU0pA4Bd7IK88AtT"},
    {name = "K-Pop Good", url = "https://music.youtube.com/playlist?list=PLE_uhVAa3GZuJeiLUVU0pA4Bd7IK88AtT"},
    {name = "Calm Ed Sheeran", url = "https://music.youtube.com/playlist?list=PLQ2uNO2v6P8phKVLtZfaadte_D5evnC5B"},
    {name = "Calm MAMAMOO", url = "https://music.youtube.com/playlist?list=PLQ2uNO2v6P8rilKj8mGgj1OwBh6QOjRM1"},
    {name = "Love", url = "https://music.youtube.com/playlist?list=PLQ2uNO2v6P8pc6FLQHTLsx6DHLffMOl-O"},
    {name = "K-Pop", url = "https://music.youtube.com/playlist?list=PLav350AkfRLltl-X9FfD0p7XVOf2i8spM"},
    {name = "2022 Recap", url = "https://music.youtube.com/playlist?list=LRYREUQZ76ap-LP7-ZHigxPxF2wnS4J8jhPSO"},
    {name = "Spring Recap '22", url = "https://music.youtube.com/playlist?list=LRSRRw6amsyUm4PjV_V7TNho4BGUN7iB8sxsH"},
    {name = "Winter Recap '22", url = "https://music.youtube.com/playlist?list=LRSRN33KzNup_dofoXuWAn9557pwXCZT2nU6w"},
    {name = "Afternoon Breeze", url = "https://www.youtube.com/playlist?list=PLRizQinsCsRmGxTIVVMNnHjUYFVXYm7vM"},
    {name = "PLAYLIST ALL ASTRO SONGS IN ORDER + OST", url = "https://music.youtube.com/playlist?list=PLxhFDDaBUk_jfp_82oRrx7uW9MbIMC3dl"},
    {name = "Superband", url = "https://music.youtube.com/playlist?list=PL9MlTrE2AP57hH4CY3NNSb4oAGs4qV_Wg"},
    {name = "루시", url = "https://music.youtube.com/playlist?list=PLRizQinsCsRnfVGv32EVoQmtW56DoSV7_"},
    {name = "Old songs lofi remix", url = "https://www.youtube.com/playlist?list=PLRizQinsCsRn7u631L68lXqZH_wnXgE6-"},
    {name = "Something Nice", url = "https://music.youtube.com/playlist?list=PLRizQinsCsRlkjencbcmt8gEqvSHgHV-X"},
    {name = "Love songs for me", url = "https://music.youtube.com/playlist?list=PLcS_llDSfjaC9xRxZedKZKS9sogMdMnwz"},
    {name = "fun, i guess", url ="https://music.youtube.com/playlist?list=PLcS_llDSfjaC9vuYarmrdWiY9ei-qUgIt"},
    {name = "2023 Recap", url = "https://music.youtube.com/playlist?list=LRYReM80mCmvXg1rnuWRPVnQsdhHkGa0QojM4"},
    {name = "recent likes 26.01.2024", url ="https://music.youtube.com/playlist?list=PLcS_llDSfjaCn0fY7KLwOmjrTWqrX1w4V"},
    {name = "Love Songs For Me, url ="https://music.youtube.com/playlist?list=PLcS_llDSfjaC9xRxZedKZKS9sogMdMnwz"},
    {name = "Good Morning from MOOMOO", url ="https://music.youtube.com/playlist?list=PLxfDVnELVJBA9Jxl8XiU-GSXowuQM_-H2},
    {name = "Good Morning from WalWal", url ="https://music.youtube.com/playlist?list=PLxfDVnELVJBAAliLnYqcw7JpBoaonylYh"},
    {name = "Good Morning from Weve", url ="https://music.youtube.com/playlist?list=PLxfDVnELVJBCB8-rf10CSolat9JzsWYWN"},
    {name = "2010s hits for me", url ="https://music.youtube.com/playlist?list=PLxfDVnELVJBC8YPSvWVNrzBGxRVF5cKut"},
    
    
    {name = "Study/Work With Youtubers and Streamers", url = "https://www.youtube.com/playlist?list=PLbX78G3bHcTn5RdEtmuKzH2gYFvw-45zG"},
    {name = "Hand Sew", url = "https://www.youtube.com/playlist?list=PLRizQinsCsRnhFQeJEevHCKHlQkcSIFOR"},

    {name = "Knit Pattern", url = "https://www.youtube.com/playlist?list=PLRizQinsCsRmWaVT0Lh6lvAXX4ach2NLJ"},
    {name = "Work Work Work Out but Inside", url = "https://www.youtube.com/playlist?list=PLRizQinsCsRmBHvK1Z4zwCG1PbIzRmU_u"},    
    {name = "Bracelet Making - Beginner", url = "https://www.youtube.com/playlist?list=PLRizQinsCsRlGF9Q-gWvEP3TXMDVVP5-N"},
    {name = "Web", url = "https://www.youtube.com/playlist?list=PLRizQinsCsRnABwbs27UzQK0SV55BOZ4i"},
    ] 
    background = "bg.mp4"